# @package filter.final
# Default final filters for VHH
# These are more stringent filters applied at the end of the pipeline

# Structure metrics
clashes:
  value: 1
  operator: '<'

sc_rmsd:
  value: 6.0
  operator: '<'

binder_near_hotspot:
  value: true
  operator: '=='

cdr3_hotspot_contacts:
  value: 0.15
  operator: '>'

percent_interface_cdr:
  value: 0.5
  operator: '>='

interface_shape_comp:
  value: 0.5
  operator: '>='

interface_hbonds:
  value: 2
  operator: '>='

# Hydrophobicity metrics
surface_hydrophobicity:
  value: 0.4
  operator: '<='

interface_hydrophobicity:
  value: 40
  operator: '>='

# Confidence metrics
pdockq2:
  value: 0.2
  operator: '>='

external_plddt:
  value: 0.87
  operator: '>'

external_iptm:
  value: 0.65
  operator: '>'

external_ptm:
  value: 0.84
  operator: '>'

external_pae:
  value: 9
  operator: '<'